name: build and test
on:
  pull_request_target:
    branches:
      - main
jobs:
  build-test:
    uses: tenfyzhong/workflows/.github/workflows/go-build-test.yml@main
    with:
      path: .
      enable-codecov: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
