name: release-go
permissions:
  contents: write
  packages: write
on:
  push:
    tags:
      - '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Get the version
        id: tag
        run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Echo tag
        run: echo ${{ steps.tag.outputs.version }}
  release:
    uses: tenfyzhong/workflows/.github/workflows/release-go.yml@main
    needs: tag
    name: release
    with:
      bin-path: .
      command: rime-dict-manager
      build-option: -ldflags "-X 'github.com/tenfyzhong/rime-dict-manager/config.Version=${{ needs.tag.outputs.version }}'"
      goos: '["darwin"]'
      goarch: '["amd64","arm64"]'
